{% set name = "krtc" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 4d95cf5f1704d1da1713d2d4cebedaa19cb129e84e1f6be1e5d22c2366c7dc81

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools_scm
  run:
    - python >=3.9
    - pykerberos

test:
  imports:
    - krtc

about:
  home: https://github.com/pcdshub/krtc
  dev_url: https://github.com/pcdshub/krtc
  summary: A small utility for using Kerberos authentication with requests
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/pcdsdevices
    - klauer
    - tangkong
    - zllentz
