{% set name = "krtc" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 951485e1457630829318e13330513b1428f858e5cb9508997a3be2f70686c567

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pykerberos

test:
  imports:
    - krtc

about:
  home: https://github.com/pcdshub/krtc
  dev_url: https://github.com/pcdshub/krtc
  summary: 'A small utility for using Kerberos authentication with requests'
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - klauer
    - tangkong
    - zllentz
    - zrylettc
