{% set name = "krtc" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: ea1d76b6396d89f43c2d1e28d5bcab85dae8e33367ef9400286fbf7fe3639cf3

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - pykerberos
    - requests

test:
  requires:
    - python {{ python_min }}
  imports:
    - krtc

about:
  home: https://github.com/pcdshub/krtc
  dev_url: https://github.com/pcdshub/krtc
  summary: A small utility for using Kerberos authentication with requests
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/pcdsdevices
    - klauer
    - tangkong
    - zllentz
