{% set name = "krtc" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 65fb02b3cc143f90b11ba7e771899e3d8d2c4d49fb7a71759e639070becc29bb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - pykerberos
    - requests

test:
  requires:
    - python {{ python_min }}
  imports:
    - krtc

about:
  home: https://github.com/pcdshub/krtc
  dev_url: https://github.com/pcdshub/krtc
  summary: A small utility for using Kerberos authentication with requests
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/pcdsdevices
